[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["@prisma/client"]
  node_bundler = "esbuild"

[dev]
  framework = "vite"
  targetPort = 5173